site_name: Census ISTAT
site_url: https://maxdragonheart.github.io/istatcelldata/
repo_url: https://github.com/MaxDragonheart/istatcelldata
repo_name: istatcelldata
site_description: Con ISTAT Cell Data puoi ottenere facilmente il set di dati riferiti ai censimenti ISTAT in cui sono stati rilasciati anche i dati delle celle censuarie.
site_author: Massimiliano Moraca
nav:
  - Home: ./index.md
  - Documentazione:
      - Intro: ./documentation/intro.md
      - References:
        - Processes: ./documentation/processes.md
        - Download: ./documentation/download.md
        - Data: ./documentation/data.md
        - GeoData: ./documentation/geodata.md
        - Generic: ./documentation/utils.md
      - Tutorial: ./tutorial/intro.md
  - Licenza: ./LICENSE.md
  - Issues: https://github.com/MaxDragonheart/istatcelldata/issues
  - Roadmap: https://github.com/MaxDragonheart/istatcelldata/milestones
theme:
  name: material
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - python
  include_homepage_in_sidebar: true
  locale: it
markdown_extensions:
  - abbr
  - admonition
  - codehilite
plugins:
    - search:
        lang: it
    - mkdocstrings:
        handlers:
          python:
            paths: [.istatcelldata]
            options:
              show_root_heading: false
              show_root_toc_entry: false
              docstring_style: google
              docstring_section_style: spacy
              annotations_path: brief
              show_source: false
    - mknotebooks:
        execute: true
        allow_errors: false