site_name: Census ISTAT
site_url: https://maxdragonheart.github.io/istat_cell_data/
repo_url: https://github.com/MaxDragonheart/istat_cell_data
repo_name: istatcelldata
site_description: Con istatcelldata puoi ottenere facilmente il set di dati riferiti ai censimenti ISTAT in cui sono stati rilasciati anche i dati delle celle censuarie.
site_author: Massimiliano Moraca
nav:
  - Home: ./index.md
  - Tutorial: ./tutorial/test.ipynb
  - Documentazione:
      - Intro: ./documentation/intro.md
      - Download: ./documentation/download.md
      - Data: ./documentation/data.md
      - GeoData: ./documentation/geodata.md
      - Generic: ./documentation/generic.md
  - Licenza: ./LICENSE.md
  - Issues: https://github.com/MaxDragonheart/istat_cell_data/issues
  - Roadmap: https://github.com/MaxDragonheart/istat_cell_data/milestones
theme:
  name: material
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - python
  include_homepage_in_sidebar: true
  locale: it
markdown_extensions:
  - abbr
  - admonition
  - codehilite
plugins:
    - search:
        lang: it
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              show_source: true
    - mknotebooks:
        execute: true
        allow_errors: false